const crypto = require('node:crypto');
const { Pool } = require('pg');
const store = require('./store');

const pool = process.env.DATABASE_URL ? new Pool({ connectionString: process.env.DATABASE_URL, max: 5, ssl: process.env.DATABASE_SSL === 'true' ? { rejectUnauthorized: true } : false }) : null;
const ALLOWED_EVENTS = new Set(['page_view','vendor_search','vendor_filter','vendor_view','vendor_contact','itinerary_generate','itinerary_save','trip_create','translation','voice_start','voice_complete','guardian_setup','checkout_start','checkout_complete','signup_start','signup_complete','consent_update']);
const SAFE_KEYS = ['path','referrer_path','category','region','intent','result_count','vendor_id','plan','provider','model','source','duration_ms','success','device','viewport','consent'];

function clean(value,max=120){return String(value||'').replace(/[<>]/g,'').trim().slice(0,max)}
function normalize(payload={}){const name=clean(payload.name,60);if(!ALLOWED_EVENTS.has(name))throw new Error('Unsupported analytics event');const properties={};for(const key of SAFE_KEYS){const value=payload.properties?.[key];if(value===undefined||value===null)continue;properties[key]=typeof value==='number'||typeof value==='boolean'?value:clean(value,180)}return{id:`evt-${crypto.randomUUID().slice(0,12)}`,name,session_id:clean(payload.session_id,120),anonymous_id:clean(payload.anonymous_id,120),properties,created_at:new Date().toISOString()}}
async function ensureSchema(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS analytics_events (id text PRIMARY KEY,name varchar(60) NOT NULL,session_id varchar(120),anonymous_id varchar(120),properties jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());CREATE INDEX IF NOT EXISTS analytics_events_created_idx ON analytics_events(created_at DESC);CREATE INDEX IF NOT EXISTS analytics_events_name_idx ON analytics_events(name);CREATE INDEX IF NOT EXISTS analytics_events_session_idx ON analytics_events(session_id);`)}
function localRecord(event){const state=store.getState();state.analytics_events||=[];state.analytics_events.push(event);if(state.analytics_events.length>100000)state.analytics_events=state.analytics_events.slice(-100000);store.saveState(state)}
async function record(payload){const event=normalize(payload);if(pool){await ensureSchema();await pool.query('INSERT INTO analytics_events(id,name,session_id,anonymous_id,properties,created_at) VALUES($1,$2,$3,$4,$5,$6)',[event.id,event.name,event.session_id||null,event.anonymous_id||null,event.properties,event.created_at])}else localRecord(event);return event}
async function allEvents(){if(pool){await ensureSchema();const result=await pool.query('SELECT id,name,session_id,anonymous_id,properties,created_at FROM analytics_events ORDER BY created_at ASC');return result.rows.map(r=>({...r,created_at:new Date(r.created_at).toISOString()}))}return(store.getState().analytics_events||[]).slice()}
async function list({limit=200,name,since}={}){let events=await allEvents();if(name)events=events.filter(e=>e.name===name);if(since)events=events.filter(e=>e.created_at>=since);return events.slice(-Math.max(1,Math.min(5000,Number(limit)||200))).reverse()}
async function summary(days=30){const since=new Date(Date.now()-Math.max(1,Math.min(365,Number(days)||30))*86400000).toISOString();const events=(await allEvents()).filter(e=>e.created_at>=since);const sessions=new Set(events.map(e=>e.session_id).filter(Boolean));const counts={},paths={},searches={},vendors={};for(const event of events){counts[event.name]=(counts[event.name]||0)+1;const p=event.properties||{};if(p.path)paths[p.path]=(paths[p.path]||0)+1;if(p.intent)searches[p.intent]=(searches[p.intent]||0)+1;if(p.vendor_id)vendors[p.vendor_id]=(vendors[p.vendor_id]||0)+1}const funnel={landing_views:counts.page_view||0,vendor_searches:counts.vendor_search||0,vendor_views:counts.vendor_view||0,itinerary_generations:counts.itinerary_generate||0,itinerary_saves:counts.itinerary_save||0,checkout_starts:counts.checkout_start||0,checkout_completions:counts.checkout_complete||0};const top=(o,n=10)=>Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,n).map(([key,count])=>({key,count}));return{since,events:events.length,sessions:sessions.size,counts,funnel,top_paths:top(paths),top_searches:top(searches),top_vendors:top(vendors),storage:pool?'postgres':'local-json'}}
module.exports={record,list,summary,ensureSchema,ALLOWED_EVENTS};
