const crypto=require('node:crypto');
const {Pool}=require('pg');
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,max:5,ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:true}:false}):null;
const mem={trips:[],checkins:[],transcripts:[]};
function allowed(){return process.env.NODE_ENV!=='production'||process.env.ALLOW_IN_MEMORY_AUTH==='true'}
function requireStorage(){if(!pool&&!allowed())throw new Error('DATABASE_URL is required for production customer data');return Boolean(pool)}
async function ensureSchema(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS customer_trips(id text PRIMARY KEY,customer_id text NOT NULL REFERENCES auth_customers(id) ON DELETE CASCADE,title text NOT NULL,destination text NOT NULL,days integer NOT NULL DEFAULT 1,start_date text,notes text,items jsonb NOT NULL DEFAULT '[]'::jsonb,created_at timestamptz NOT NULL DEFAULT now());CREATE INDEX IF NOT EXISTS customer_trips_owner_idx ON customer_trips(customer_id,created_at DESC);CREATE TABLE IF NOT EXISTS customer_checkins(id text PRIMARY KEY,customer_id text NOT NULL REFERENCES auth_customers(id) ON DELETE CASCADE,traveler_name text NOT NULL,contact text NOT NULL,hours integer NOT NULL,note text,state text NOT NULL DEFAULT 'scheduled',created_at timestamptz NOT NULL DEFAULT now());CREATE INDEX IF NOT EXISTS customer_checkins_owner_idx ON customer_checkins(customer_id,created_at DESC);CREATE TABLE IF NOT EXISTS customer_transcripts(id text PRIMARY KEY,customer_id text NOT NULL REFERENCES auth_customers(id) ON DELETE CASCADE,session_id text NOT NULL,role text NOT NULL,content text NOT NULL,source text,created_at timestamptz NOT NULL DEFAULT now());CREATE INDEX IF NOT EXISTS customer_transcripts_owner_idx ON customer_transcripts(customer_id,session_id,created_at);`)}
const id=p=>`${p}-${crypto.randomUUID()}`;const now=()=>new Date().toISOString();
async function listTrips(customerId){if(requireStorage()){await ensureSchema();return(await pool.query('SELECT id,title,destination,days,start_date AS "startDate",notes,items,created_at FROM customer_trips WHERE customer_id=$1 ORDER BY created_at DESC',[customerId])).rows}return mem.trips.filter(x=>x.customer_id===customerId)}
async function createTrip(customerId,p={}){const row={id:id('trip'),customer_id:customerId,title:String(p.title||'My Trip').trim().slice(0,160),destination:String(p.destination||'Jamaica').trim().slice(0,160),days:Math.max(1,Math.min(30,Number(p.days)||1)),startDate:String(p.startDate||p.start_date||'').slice(0,20),notes:String(p.notes||'').slice(0,4000),items:Array.isArray(p.items)?p.items.slice(0,100):[],created_at:now()};if(requireStorage()){await ensureSchema();await pool.query('INSERT INTO customer_trips(id,customer_id,title,destination,days,start_date,notes,items,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)',[row.id,customerId,row.title,row.destination,row.days,row.startDate,row.notes,JSON.stringify(row.items),row.created_at])}else mem.trips.unshift(row);return row}
async function addTripItem(customerId,tripId,p={}){const trips=await listTrips(customerId),trip=trips.find(x=>x.id===tripId);if(!trip)return null;const item={id:id('item'),title:String(p.title||p.name||'Stop').slice(0,180),note:String(p.note||'').slice(0,1000),place_id:String(p.place_id||p.placeId||'').slice(0,120),done:Boolean(p.done)};trip.items=Array.isArray(trip.items)?trip.items:[];trip.items.push(item);if(requireStorage())await pool.query('UPDATE customer_trips SET items=$1 WHERE id=$2 AND customer_id=$3',[JSON.stringify(trip.items),tripId,customerId]);return{trip,item}}
async function listCheckins(customerId){if(requireStorage()){await ensureSchema();return(await pool.query('SELECT id,traveler_name,contact,hours,note,state,created_at FROM customer_checkins WHERE customer_id=$1 ORDER BY created_at DESC',[customerId])).rows}return mem.checkins.filter(x=>x.customer_id===customerId)}
async function createCheckin(customerId,p={}){const row={id:id('checkin'),customer_id:customerId,traveler_name:String(p.traveler_name||p.name||'Traveler').slice(0,120),contact:String(p.contact||'').slice(0,240),hours:Math.max(1,Math.min(24,Number(p.hours)||1)),note:String(p.note||'').slice(0,1000),state:'scheduled',created_at:now()};if(!row.contact)throw new Error('contact is required');if(requireStorage()){await ensureSchema();await pool.query('INSERT INTO customer_checkins(id,customer_id,traveler_name,contact,hours,note,state,created_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8)',[row.id,customerId,row.traveler_name,row.contact,row.hours,row.note,row.state,row.created_at])}else mem.checkins.unshift(row);return row}
async function saveTranscript(customerId,p={}){const row={id:id('transcript'),customer_id:customerId,session_id:String(p.session_id||'default').slice(0,120),role:p.role==='assistant'?'assistant':'user',content:String(p.content||'').trim().slice(0,10000),source:String(p.source||'text').slice(0,40),created_at:now()};if(!row.content)throw new Error('content is required');if(requireStorage()){await ensureSchema();await pool.query('INSERT INTO customer_transcripts(id,customer_id,session_id,role,content,source,created_at) VALUES($1,$2,$3,$4,$5,$6,$7)',[row.id,customerId,row.session_id,row.role,row.content,row.source,row.created_at])}else mem.transcripts.push(row);return row}
async function listTranscripts(customerId,sessionId){if(requireStorage()){await ensureSchema();return(await pool.query('SELECT id,session_id,role,content,source,created_at FROM customer_transcripts WHERE customer_id=$1 AND session_id=$2 ORDER BY created_at',[customerId,sessionId])).rows}return mem.transcripts.filter(x=>x.customer_id===customerId&&x.session_id===sessionId)}
module.exports={ensureSchema,listTrips,createTrip,addTripItem,listCheckins,createCheckin,saveTranscript,listTranscripts,storageMode:()=>pool?'postgres':'memory'};
